server:
   port: 9888

logging:
   level:
      com.v5ent.movie: DEBUG

spring:
   datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/seacms?characterEncoding=UTF-8&serverTimezone=UTC&useUnicode=true&useSSL=false
      username: root
      password: v5ent
      
mybatis:
   type-aliases-package: com.v5ent.movie.entity
   mapper-locations: classpath:mapper/*.xml